spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vfonsecapv/config
          repos:
            local:
              pattern: local*
              uri: https://github.com/vfonsecapv/config
server:
 port: 9000
management:
 context-path: /adm