spring:
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
 cloud:
  config:
    server:
      git:
        uri: https://github.com/vfonsecapv/config.git
        repos:
          local:
            pattern: local*
            uri: https://github.com/vfonsecapv/config.git
server:
 port: 9000