spring:
 cloud:
  config:
    server:
      git:
        uri: https://github.com/vfonsecapv/config
        repos:
          local:
            pattern: local*
            uri: https://github.com/vfonsecapv/
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'