spring:
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
 cloud:
  config:
    server:
      git:
        uri: file:/Users/victorfonseca/git/config-repo
        repos:
          local:
            pattern: local*
            uri: file:/Users/victorfonseca/git/config-repo
server:
 port: 9000